# Generated by Django 5.1.5 on 2025-02-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='intent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
